var searchData=
[
  ['s_2052_20maplink_20s52_20api_0',['S-52 MapLink S52 API',['../group__group__s52sdk.html',1,'']]],
  ['s52_20api_1',['S-52 MapLink S52 API',['../group__group__s52sdk.html',1,'']]],
  ['s52_20apis_2',['MapLink S52 APIs',['../group__apigroup__maplink__s52__apis.html',1,'']]],
  ['s63_20api_3',['S63 API',['../group__group__s63sdk.html',1,'']]],
  ['s63_20apis_4',['MapLink S63 APIs',['../group__apigroup__maplink__s63__apis.html',1,'']]],
  ['satellite_20propagator_20api_5',['MapLink Satellite Propagator API',['../group__group__satellitepropagatorsdk.html',1,'']]],
  ['schema_20information_6',['Application Schema Information',['../group__group__meta__19115__applicationschemainformation.html',1,'']]],
  ['schema_20language_7',['ISO19103 Conceptual Schema Language',['../group__group__meta__19103.html',1,'']]],
  ['sdk_8',['SDK',['../group__group__ogc__geopackagesdk.html',1,'Geo Package SDK'],['../group__group__ogc__wmts.html',1,'WMTS Data Layer SDK']]],
  ['search_20api_9',['LandLink Address Search API',['../group__group__landlinkqas.html',1,'']]],
  ['selection_20operations_10',['Selection Operations',['../group__apigroup__editor__selection__operations.html',1,'']]],
  ['service_20providers_11',['Service Providers',['../group__group__maf__serviceproviders.html',1,'']]],
  ['set_20information_12',['Metadata Entity Set Information',['../group__group__meta__19115__metadataentitysetinformation.html',1,'']]],
  ['sink_13',['Post Office Notification Sink',['../group__group__maf__postoffice.html',1,'']]],
  ['spatial_20editor_20api_14',['MapLink Spatial Editor API',['../group__group__spatialeditorsdk.html',1,'']]],
  ['spatial_20ref_20by_20coordinates_15',['ISO19111 Spatial Ref by Coordinates',['../group__group__meta__19111.html',1,'']]],
  ['spatial_20representation_20information_16',['Spatial Representation Information',['../group__group__meta__19115__spatialrepresentationinformation.html',1,'']]],
  ['specialised_20primitive_20operations_17',['Specialised Primitive Operations',['../group__group__landlinkapi__specialisedprimitiveops.html',1,'']]],
  ['surface_20api_18',['MapLink OpenGL Drawing Surface API',['../group__apigroup__maplink__opengl__drawing__surface__api.html',1,'']]],
  ['surface_20notifications_19',['Drawing Surface Notifications',['../group__group__maf__drawingsurfacenotifications.html',1,'']]],
  ['system_20',['Temporal Reference System',['../group__group__meta__19108__temporalreferencesystem.html',1,'']]],
  ['system_20information_21',['Reference System Information',['../group__group__meta__19115__referencesysteminformation.html',1,'']]]
];
