var searchData=
[
  ['macros_0',['MapLink API DLL Macros',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLink.h#autotoc_md39',1,'']]],
  ['management_1',['History Management',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLink.h#autotoc_md42',1,'']]],
  ['manager_2',['Using the Track Display Manager',['../trackdisplaymanager_page.html',1,'trackmanagerdeveloperguide_page']]],
  ['manager_20basics_3',['Track Display Manager Basics',['../trackdisplaymanager_page.html#trackdisplaymanager_basics',1,'']]],
  ['map_20chart_20types_20series_20code_4',['Map Chart Types Series Code',['../class_t_s_l_c_a_d_r_g_exporter.html#autotoc_md125',1,'Map/Chart Types (Series Code)'],['../class_t_s_l_r_d_t_e_d_exporter.html#autotoc_md135',1,'Map/Chart Types (Series Code)']]],
  ['map_20creation_20requirements_5',['MapLink Studio Map Creation requirements',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_maplink_studio',1,'']]],
  ['map_20datalater_6',['Howto setup a Map DataLater',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_howto_setup_a_map_datalayer',1,'']]],
  ['map_20projection_3a_7',['Map Projection:',['../class_t_s_l_transform_traits.html#autotoc_md75',1,'']]],
  ['map_20requirements_8',['Map Requirements',['../class_t_s_l_c_a_d_r_g_exporter.html#autotoc_md120',1,'']]],
  ['maplink_20api_20dll_20macros_9',['MapLink API DLL Macros',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLink.h#autotoc_md39',1,'']]],
  ['maplink_20notes_3a_10',['MapLink Notes:',['../class_t_s_l_d_x_accelerated_surface.html#autotoc_md105',1,'MapLink Notes:'],['../class_t_s_l_w_g_l_accelerated_surface.html#autotoc_md109',1,'MapLink Notes:'],['../class_t_s_l_x11_g_l_accelerated_surface.html#autotoc_md114',1,'MapLink Notes:']]],
  ['maplink_20pro_11',['MapLink Pro',['../index.html',1,'']]],
  ['maplink_20pro_20supported_20file_20formats_12',['MapLink Pro Supported File Formats',['../fileformats_page.html',1,'']]],
  ['maplink_20specific_20type_20definitions_13',['Operating System (OS) and MapLink specific type definitions',['../_map_link_8h.html#autotoc_md37',1,'']]],
  ['maplink_20studio_20map_20creation_20requirements_14',['MapLink Studio Map Creation requirements',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_maplink_studio',1,'']]],
  ['mask_20data_20from_20a_20file_15',['Loading Mask data from a File',['../class_t_s_l_direct_import_raster.html#autotoc_md89',1,'']]],
  ['max_20and_20min_20values_16',['Max and Min values',['../tslatomic_8h.html#autotoc_md25',1,'']]],
  ['memory_20cache_17',['In Memory Cache',['../class_t_s_l_direct_import_data_layer.html#autotoc_md86',1,'']]],
  ['mercator_20display_20issues_20near_20the_20poles_18',['Mercator display issues near the poles',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_display_issues',1,'']]],
  ['mercator_20notes_19',['Transverse Mercator Notes',['../class_t_s_l_coordinate_system.html#autotoc_md62',1,'']]],
  ['method_20in_20the_20application_20is_3a_20',['An example of handling this method in the application is:',['../class_t_s_l_w_m_s_service_user_settings_callbacks.html#autotoc_md76',1,'']]],
  ['method_20notes_3a_21',['Method Notes:',['../class_t_s_l_accelerated_surface.html#autotoc_md99',1,'']]],
  ['microsoft_20windows_22',['Microsoft Windows',['../_map_link_8h.html#autotoc_md35',1,'']]],
  ['min_20values_23',['Max and Min values',['../tslatomic_8h.html#autotoc_md25',1,'']]],
  ['module_20names_24',['List of Module Names',['../group__group__maplink__cpp__modules.html#autotoc_md1',1,'']]],
  ['module_20naming_20conventions_25',['Module naming conventions',['../group__group__maplink__cpp__modules.html#autotoc_md0',1,'']]],
  ['multi_20thread_20guidelines_26',['Multi-Thread Guidelines',['../class_t_s_l_accelerated_m_t_render_control.html#autotoc_md95',1,'']]]
];
