var searchData=
[
  ['safety_0',['Safety',['../class_t_s_l_drawing_surface_base.html#autotoc_md64',1,'Thread Safety'],['../classenvitia_1_1maplink_1_1earth_1_1_surface.html#autotoc_md151',1,'Thread Safety']]],
  ['scale_20bands_1',['Data Layout and scale bands',['../class_t_s_l_direct_import_data_layer.html#autotoc_md78',1,'']]],
  ['scales_2',['Scales',['../group__group__cadrgexportersdk.html#autotoc_md127',1,'Non Standard Scales'],['../group__group__cadrgexportersdk.html#autotoc_md128',1,'Permitted Scales']]],
  ['sdk_20developer_20guide_3',['Tracks SDK Developer Guide',['../trackmanagerdeveloperguide_page.html',1,'']]],
  ['selection_20symbols_4',['Selection Symbols',['../trackdisplaymanager_page.html#trackdisplaymanager_basics_visualisation_selectionsymbols',1,'']]],
  ['series_20code_5',['Series Code',['../class_t_s_l_c_a_d_r_g_exporter.html#autotoc_md125',1,'Map/Chart Types (Series Code)'],['../class_t_s_l_r_d_t_e_d_exporter.html#autotoc_md135',1,'Map/Chart Types (Series Code)']]],
  ['setting_20track_20positions_6',['Setting Track Positions',['../trackdisplaymanager_page.html#trackdisplaymanager_basics_updating_tracks',1,'']]],
  ['setting_20up_20a_20tslstandarddatalayer_7',['Setting up a TSLStandardDataLayer',['../class_t_s_l_open_g_l_surface.html#realtime_reprojeciton_setting_up_a_standarddatalayer',1,'']]],
  ['settings_8',['Raster specific settings',['../class_t_s_l_direct_import_data_layer.html#autotoc_md84',1,'']]],
  ['settings_20and_20styling_9',['Vector specific settings and styling',['../class_t_s_l_direct_import_data_layer.html#autotoc_md81',1,'']]],
  ['setup_10',['Windows Compiler Setup',['../tslstring_8h.html#autotoc_md61',1,'']]],
  ['setup_20a_20map_20datalater_11',['Howto setup a Map DataLater',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_howto_setup_a_map_datalayer',1,'']]],
  ['should_3a_12',['The user should:',['../class_t_s_l_accelerated_surface.html#autotoc_md98',1,'']]],
  ['single_20precision_20float_2032bits_13',['Single precision float (32bits)',['../tslatomic_8h.html#autotoc_md7',1,'']]],
  ['sizing_14',['Cache Sizing',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_cache_sizing',1,'']]],
  ['special_20text_20fields_20in_20custom_20symbols_15',['Special Text Fields in Custom Symbols',['../trackdisplaymanager_page.html#text_replacement_sec',1,'']]],
  ['specific_16',['Raster type specific',['../class_t_s_l_direct_import_raster.html#autotoc_md90',1,'']]],
  ['specific_20notes_17',['Data layer specific notes',['../class_t_s_l_drawing_surface_tiled_buffer_control.html#autotoc_md66',1,'']]],
  ['specific_20settings_18',['Raster specific settings',['../class_t_s_l_direct_import_data_layer.html#autotoc_md84',1,'']]],
  ['specific_20settings_20and_20styling_19',['Vector specific settings and styling',['../class_t_s_l_direct_import_data_layer.html#autotoc_md81',1,'']]],
  ['specific_20type_20definitions_20',['Operating System (OS) and MapLink specific type definitions',['../_map_link_8h.html#autotoc_md37',1,'']]],
  ['specific_20types_21',['Specific Types',['../class_t_s_l_drawing_surface_base.html#autotoc_md65',1,'OS Specific Types'],['../classenvitia_1_1maplink_1_1earth_1_1_surface.html#autotoc_md152',1,'OS Specific Types']]],
  ['standard_20scales_22',['Non Standard Scales',['../group__group__cadrgexportersdk.html#autotoc_md127',1,'']]],
  ['storing_20and_20viewing_20track_20history_23',['Storing and Viewing Track History',['../trackdisplaymanager_page.html#trackdisplaymanager_history',1,'']]],
  ['structure_24',['Structure',['../class_t_s_l_c_a_d_r_g_exporter.html#autotoc_md121',1,'Output Directory Structure'],['../class_t_s_l_harris_image_exporter.html#autotoc_md130',1,'Output Directory Structure'],['../class_t_s_l_r_d_t_e_d_exporter.html#autotoc_md132',1,'Output Directory Structure']]],
  ['studio_20map_20creation_20requirements_25',['MapLink Studio Map Creation requirements',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_maplink_studio',1,'']]],
  ['stuff_26',['Common stuff',['../namespacestd.html#autotoc_md142',1,'']]],
  ['styling_27',['Vector specific settings and styling',['../class_t_s_l_direct_import_data_layer.html#autotoc_md81',1,'']]],
  ['support_20windows_20only_20at_20present_28',['Print support - Windows only at present',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLinkDrawing.h#autotoc_md57',1,'']]],
  ['supported_29',['DataLayers Supported',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_layers_supported',1,'']]],
  ['supported_20data_20formats_30',['Supported Data Formats',['../class_t_s_l_direct_import_data_layer.html#autotoc_md77',1,'']]],
  ['supported_20file_20formats_31',['MapLink Pro Supported File Formats',['../fileformats_page.html',1,'']]],
  ['surface_32',['Associating a TrackDisplayManager with a drawing surface',['../trackdisplaymanager_page.html#trackdisplaymanager_basics_association',1,'']]],
  ['surface_3a_33',['Requirements for Surface:',['../class_t_s_l_x11_g_l_accelerated_surface.html#autotoc_md113',1,'']]],
  ['surfaces_20rendering_20interface_34',['Drawing Surfaces &amp;amp; Rendering Interface',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLinkDrawing.h#autotoc_md56',1,'']]],
  ['symbols_35',['Symbols',['../trackdisplaymanager_page.html#trackdisplaymanager_custom_symbols',1,'Creating Custom Symbols'],['../trackdisplaymanager_page.html#trackdisplaymanager_basics_visualisation_historysymbols',1,'History Symbols'],['../trackdisplaymanager_page.html#trackdisplaymanager_basics_visualisation_pointsymbols',1,'Point Symbols'],['../trackdisplaymanager_page.html#trackdisplaymanager_basics_visualisation_selectionsymbols',1,'Selection Symbols'],['../trackdisplaymanager_page.html#text_replacement_sec',1,'Special Text Fields in Custom Symbols']]],
  ['system_36',['The Coordinate System',['../C:/Azure/azureAgent/vsts-agent-win-x64-3.246.0/_work/13/s/SDK/CoreSDK/api/MapLink.h#autotoc_md49',1,'']]],
  ['system_20os_20and_20maplink_20specific_20type_20definitions_37',['Operating System (OS) and MapLink specific type definitions',['../_map_link_8h.html#autotoc_md37',1,'']]],
  ['systems_38',['Coordinate Providing Layer and Coordinate Systems',['../class_t_s_l_open_g_l_surface.html#realtime_reprojection_coordinate_provifing_layer',1,'']]]
];
