"""Fix bare C++ code blocks in terrain-sdk.md"""

with open(r'c:\maplink\maplink-docs\pages\developers-guide\terrain-sdk.md', 'rb') as f:
    content = f.read()

fixes = []

# Fix 1: Lines 33-53: TSLTerrainDatabase creation and open
fixes.append(('Fix1 TSLTerrainDatabase creation and open',
    b'Add the following to your application to create an instance of the Terrain SDK main class and load some data into it:\r\n\r\n'
    b'TSLTerrainDatabase\\* terrainDB = new TSLTerrainDatabase;\r\n\r\n'
    b'if ( terrainDB-\\>open( "terraindb.tdb" ) != TSLTerrain_OK )\\\r\n'
    b'{\r\n\r\n'
    b'// Handle file open error\r\n\r\n'
    b'}\r\n\r\n'
    b'else\\\r\n'
    b'{\r\n\r\n'
    b'// Terrain database is open and ready to query. Start by getting\r\n\r\n'
    b'// the extent of the database\r\n\r\n'
    b'double x1, y1, x2, y2;\r\n\r\n'
    b'terrainDB-\\>queryExtent( x1, y1, x2, y2 );\r\n\r\n'
    b'}\r\n\r\n'
    b'Once you have performed these two steps',
    b'Add the following to your application to create an instance of the Terrain SDK main class and load some data into it:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDatabase* terrainDB = new TSLTerrainDatabase;\r\n\r\n'
    b'if ( terrainDB->open( "terraindb.tdb" ) != TSLTerrain_OK )\r\n'
    b'{\r\n\r\n'
    b'// Handle file open error\r\n\r\n'
    b'}\r\n\r\n'
    b'else\r\n'
    b'{\r\n\r\n'
    b'// Terrain database is open and ready to query. Start by getting\r\n\r\n'
    b'// the extent of the database\r\n\r\n'
    b'double x1, y1, x2, y2;\r\n\r\n'
    b'terrainDB->queryExtent( x1, y1, x2, y2 );\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'Once you have performed these two steps'
))

# Fix 2: Lines 91-116: coordinate system query
fixes.append(('Fix2 coordinate system query',
    b'Add this code after the call to terrainDB-\\>open() to ensure the loaded terrain database is using the default coordinate system:\r\n\r\n'
    b'TSLCoordinateSystem\\* cs = terrainDB-\\>queryCoordinateSystem();\r\n\r\n'
    b'// In most cases cs will not be NULL but older versions of the\r\n\r\n'
    b'// Terrain Database did not support coordinate system queries\r\n\r\n'
    b'// therefore we must check the return value of\r\n\r\n'
    b'// queryCoordinateSystem()\r\n\r\n'
    b'if ( cs )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Make sure the coordinate system is the default coordinate\r\n\r\n'
    b'// system so we can assume the Map Units are in Latitude/Longitude\r\n\r\n'
    b'if ( stricmp( cs-\\>name(), "Default Coordinate System" ) != 0 )\\\r\n'
    b'{\r\n\r\n'
    b'// Not the default coordinate system - display an error\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'The TSLCoordinateSystem object returned',
    b'Add this code after the call to terrainDB->open() to ensure the loaded terrain database is using the default coordinate system:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLCoordinateSystem* cs = terrainDB->queryCoordinateSystem();\r\n\r\n'
    b'// In most cases cs will not be NULL but older versions of the\r\n\r\n'
    b'// Terrain Database did not support coordinate system queries\r\n\r\n'
    b'// therefore we must check the return value of\r\n\r\n'
    b'// queryCoordinateSystem()\r\n\r\n'
    b'if ( cs )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Make sure the coordinate system is the default coordinate\r\n\r\n'
    b'// system so we can assume the Map Units are in Latitude/Longitude\r\n\r\n'
    b'if ( stricmp( cs->name(), "Default Coordinate System" ) != 0 )\r\n'
    b'{\r\n\r\n'
    b'// Not the default coordinate system - display an error\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'The TSLCoordinateSystem object returned'
))

# Fix 3: Lines 122-147: latLongToMU/MUToLatLong using TSLCoordinateSystem
fixes.append(('Fix3 TSLCoordinateSystem latLongToMU MUToLatLong',
    b'The first method for transforming coordinates uses TSLCoordinateSystem:\r\n\r\n'
    b'TSLCoordinateSystem\\* cs = terrainDB-\\>queryCoordinateSystem();\r\n\r\n'
    b'if ( cs )\r\n\r\n'
    b'{\r\n\r\n'
    b'double muOutX, muOutY;\r\n\r\n'
    b'double latOut, lonOut;\r\n\r\n'
    b'if ( cs-\\>latLongToMU( latIn, lonIn, &muOutX, &muOutY ) )\\\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( cs-\\>MUToLatLong( muInX, muInY, &latOut, &lonOut ) )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'> The second method for transforming coordinates is more convenient:',
    b'The first method for transforming coordinates uses TSLCoordinateSystem:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLCoordinateSystem* cs = terrainDB->queryCoordinateSystem();\r\n\r\n'
    b'if ( cs )\r\n\r\n'
    b'{\r\n\r\n'
    b'double muOutX, muOutY;\r\n\r\n'
    b'double latOut, lonOut;\r\n\r\n'
    b'if ( cs->latLongToMU( latIn, lonIn, &muOutX, &muOutY ) )\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( cs->MUToLatLong( muInX, muInY, &latOut, &lonOut ) )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'> The second method for transforming coordinates is more convenient:'
))

# Fix 4: Lines 151-172: terrainDB latLongToMU/MUToLatLong
fixes.append(('Fix4 terrainDB latLongToMU MUToLatLong',
    b'> The second method for transforming coordinates is more convenient:\r\n\r\n'
    b'double muOutX, muOutY;\r\n\r\n'
    b'double latOut, lonOut;\r\n\r\n'
    b'if ( terrainDB-\\>latLongToMU( latIn, lonIn, &muOutX, &muOutY ) ==\r\n\r\n'
    b'TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( terrainDB-\\>MUToLatLong( muInX, muInY, &latOut, &lonOut ) ==\r\n\r\n'
    b'TSLTerrain_OK )\r\n\r\n'
    b'{\\\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'## How Do I Access the Data?',
    b'> The second method for transforming coordinates is more convenient:\r\n\r\n'
    b'```cpp\r\n'
    b'double muOutX, muOutY;\r\n\r\n'
    b'double latOut, lonOut;\r\n\r\n'
    b'if ( terrainDB->latLongToMU( latIn, lonIn, &muOutX, &muOutY ) ==\r\n\r\n'
    b'TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( terrainDB->MUToLatLong( muInX, muInY, &latOut, &lonOut ) ==\r\n\r\n'
    b'TSLTerrain_OK )\r\n\r\n'
    b'{\r\n'
    b'// Conversion successful\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'## How Do I Access the Data?'
))

# Fix 5: Lines 185-197: queryLine
fixes.append(('Fix5 queryLine',
    b'To query a line of 10 points from the database:\r\n\r\n'
    b'TSLTerrainDataItem dataItem\\[10\\];\r\n\r\n'
    b'if ( terrainDB-\\>queryLine( muXstart, muYstart, muXend, muYend,\r\n\r\n'
    b'10, dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in the dataItem array\r\n\r\n'
    b'}\r\n\r\n'
    b'To query a single point from the database:',
    b'To query a line of 10 points from the database:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem[10];\r\n\r\n'
    b'if ( terrainDB->queryLine( muXstart, muYstart, muXend, muYend,\r\n\r\n'
    b'10, dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in the dataItem array\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'To query a single point from the database:'
))

# Fix 6: Lines 201-211: single point query
fixes.append(('Fix6 single point query',
    b'To query a single point from the database:\r\n\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if ( terrainDB-\\>query( muX, muY, &dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in dataItem\r\n\r\n'
    b'}\r\n\r\n'
    b'To query a 10 x 5 grid from the database:',
    b'To query a single point from the database:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if ( terrainDB->query( muX, muY, &dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in dataItem\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'To query a 10 x 5 grid from the database:'
))

# Fix 7: Lines 215-227: queryArea
fixes.append(('Fix7 queryArea',
    b'To query a 10 x 5 grid from the database:\r\n\r\n'
    b'TSLTerrainDataItem dataItem\\[10\\*5\\];\r\n\r\n'
    b'if ( terrainDB-\\>queryArea( muBlX, muBlY, muTrX, muTrY,\r\n\r\n'
    b'10, 5, dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in the dataItem array. The data is stored row-by-row\r\n\r\n'
    b'}\r\n\r\n'
    b'In each case, the data is returned',
    b'To query a 10 x 5 grid from the database:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem[10*5];\r\n\r\n'
    b'if ( terrainDB->queryArea( muBlX, muBlY, muTrX, muTrY,\r\n\r\n'
    b'10, 5, dataItem ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. The information about the point is\r\n\r\n'
    b'// stored in the dataItem array. The data is stored row-by-row\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'In each case, the data is returned'
))

# Fix 8: Lines 269-281: query with TSLTerrainData_All
fixes.append(('Fix8 query with TSLTerrainData_All',
    b'To query a single point from the database getting all available associated information:\r\n\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if ( terrainDB-\\>query( muX, muY, &dataItem, TSLTerrainData_All )\r\n\r\n'
    b'== TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. All information about the point is\r\n\r\n'
    b'// stored in dataItem\r\n\r\n'
    b'}\r\n\r\n'
    b'## How Accurate is My Data?',
    b'To query a single point from the database getting all available associated information:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if ( terrainDB->query( muX, muY, &dataItem, TSLTerrainData_All )\r\n\r\n'
    b'== TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. All information about the point is\r\n\r\n'
    b'// stored in dataItem\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'## How Accurate is My Data?'
))

# Fix 9: Lines 293-303: query with TSLTerrainData_Min, highestRes=true
fixes.append(('Fix9 query highestRes true',
    b'To query a single point from the database using the highest resolution layer available. Note the "true" parameter to the query function that informs the Terrain SDK that we want the highest resolution data.\r\n\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if (terrainDB-\\>query(muX, muY, &dataItem, TSLTerrainData_Min, true)\r\n\r\n'
    b'== TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. Highest resolution data obtained\r\n\r\n'
    b'}\r\n\r\n'
    b'> To query a single point from the database getting all available associated information:',
    b'To query a single point from the database using the highest resolution layer available. Note the "true" parameter to the query function that informs the Terrain SDK that we want the highest resolution data.\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'if (terrainDB->query(muX, muY, &dataItem, TSLTerrainData_Min, true)\r\n\r\n'
    b'== TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful. Highest resolution data obtained\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'> To query a single point from the database getting all available associated information:'
))

# Fix 10: Lines 307-329: query with bilinear interpolation and TSLTerrainData_Nearest
fixes.append(('Fix10 query bilinear interpolation',
    b'> To query a single point from the database getting all available associated information:\r\n\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'// Use bilinear interpolation for a more accurate result\r\n\r\n'
    b'if ( terrainDB-\\>query( muX, muY, &dataItem,\r\n\r\n'
    b'TSLTerrainData_Min \\| TSLTerrainData_Nearest, false,\r\n\r\n'
    b'TSLTerrainInterpolate_LINEAR ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful.\r\n\r\n'
    b'// m_x and m_y contain the requested location.\r\n\r\n'
    b'// m_z contains a value obtained by bilinear interpolation\r\n\r\n'
    b'// m_nearestX, m_nearestY and m_nearestZ contain the location\r\n\r\n'
    b'// and height/depth of the nearest stored data in the database\r\n\r\n'
    b'}\r\n\r\n'
    b'Onto the other question:',
    b'> To query a single point from the database getting all available associated information:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLTerrainDataItem dataItem;\r\n\r\n'
    b'// Use bilinear interpolation for a more accurate result\r\n\r\n'
    b'if ( terrainDB->query( muX, muY, &dataItem,\r\n\r\n'
    b'TSLTerrainData_Min | TSLTerrainData_Nearest, false,\r\n\r\n'
    b'TSLTerrainInterpolate_LINEAR ) == TSLTerrain_OK )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Query successful.\r\n\r\n'
    b'// m_x and m_y contain the requested location.\r\n\r\n'
    b'// m_z contains a value obtained by bilinear interpolation\r\n\r\n'
    b'// m_nearestX, m_nearestY and m_nearestZ contain the location\r\n\r\n'
    b'// and height/depth of the nearest stored data in the database\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'Onto the other question:'
))

# Fix 11: Lines 339-378: zoom and getMUExtent/displayExtent
fixes.append(('Fix11 zoom getMUExtent displayExtent',
    b'In the handler for the MapLink map zoom command, notify the Terrain SDK of the new extent.\r\n\r\n'
    b'if ( m_drawingSurface-\\>zoom( 25, true, false ) )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Zoom was successful. Tell the Terrain SDK\r\n\r\n'
    b'// The function that notifies the Terrain SDK requires the size\r\n\r\n'
    b'// of the map window and the new extent. Assume the map window\r\n\r\n'
    b'// is the same size as this window\r\n\r\n'
    b'CRect rc;\r\n\r\n'
    b'GetClientRect( rc );\r\n\r\n'
    b'// Get the extent of the data. We need to convert this to MU. This\r\n\r\n'
    b'// assumes the MU of the map and of the Terrain SDK are the same\r\n\r\n'
    b'double muX1, muY1, muX2, muY2;\r\n\r\n'
    b'if ( m_drawingSurface-\\>getMUExtent( &muX1, &muY1, &muX2, &muY2 ) )\\\r\n'
    b'{\r\n\r\n'
    b'// We have enough information now\r\n\r\n'
    b'terrainDB-\\>displayExtent( rc.Width(), rc.Height(), muX1, muY1,\r\n\r\n'
    b'muX2, muY2 );\r\n\r\n'
    b'// That\'s it! Terrain database optimised for this\r\n\r\n'
    b'// screen resolution\r\n\r\n'
    b'}\r\n\r\n'
    b'InvalidateRect( 0, FALSE ) ;\r\n\r\n'
    b'}\r\n\r\n'
    b'## Contouring',
    b'In the handler for the MapLink map zoom command, notify the Terrain SDK of the new extent.\r\n\r\n'
    b'```cpp\r\n'
    b'if ( m_drawingSurface->zoom( 25, true, false ) )\r\n\r\n'
    b'{\r\n\r\n'
    b'// Zoom was successful. Tell the Terrain SDK\r\n\r\n'
    b'// The function that notifies the Terrain SDK requires the size\r\n\r\n'
    b'// of the map window and the new extent. Assume the map window\r\n\r\n'
    b'// is the same size as this window\r\n\r\n'
    b'CRect rc;\r\n\r\n'
    b'GetClientRect( rc );\r\n\r\n'
    b'// Get the extent of the data. We need to convert this to MU. This\r\n\r\n'
    b'// assumes the MU of the map and of the Terrain SDK are the same\r\n\r\n'
    b'double muX1, muY1, muX2, muY2;\r\n\r\n'
    b'if ( m_drawingSurface->getMUExtent( &muX1, &muY1, &muX2, &muY2 ) )\r\n'
    b'{\r\n\r\n'
    b'// We have enough information now\r\n\r\n'
    b'terrainDB->displayExtent( rc.Width(), rc.Height(), muX1, muY1,\r\n\r\n'
    b'muX2, muY2 );\r\n\r\n'
    b'// That\'s it! Terrain database optimised for this\r\n\r\n'
    b'// screen resolution\r\n\r\n'
    b'}\r\n\r\n'
    b'InvalidateRect( 0, FALSE ) ;\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'## Contouring'
))

# Fix 12: Lines 805-877: Single Point-to-point Line of Sight
fixes.append(('Fix12 Single LOS viewshed',
    b'### Single Point-to-point Line of Sight\r\n\r\n'
    b'// Set up the input object, using the current display size, and extent\r\n\r\n'
    b'// The provided extent/display size will determine which level of detail\r\n\r\n'
    b'// is used within the terrain database.\r\n\r\n'
    b'TSLTerrainVSInputTerrainDatabase\\* input =\r\n\r\n'
    b'new TSLTerrainVSInputTerrainDatabase(&m_terrainDatabase,\r\n\r\n'
    b'displayExtent, displayWidth, displayHeight);\r\n\r\n'
    b'// Setup the viewshed algorithm\r\n\r\n'
    b'// For single LOS calculations, the RFVS algorithm doesn\'t require\r\n\r\n'
    b'// a compositor object.\r\n\r\n'
    b'// It does however require an input object, to calculate whether\r\n\r\n'
    b'// the line is blocked by terrain.\r\n\r\n'
    b'TSLTerrainVSAlgorithmRFVS algorithm(input, NULL);\r\n\r\n'
    b'// Determine whether the end point can be seen from the start point.\r\n\r\n'
    b'// If it cannot, the \'blocked\' point will be populated\r\n\r\n'
    b'double LOSStartX = -122.0;\r\n\r\n'
    b'double LOSStartY = 37.0;\r\n\r\n'
    b'double LOSStartZ = 100.0;\r\n\r\n'
    b'double LOSEndX = -121.5;\r\n\r\n'
    b'double LOSEndY = 37.35;\r\n\r\n'
    b'double LOSEndZ = 0.0; // Sea level\r\n\r\n'
    b'// Storage for the \'blocked\' point\r\n\r\n'
    b'double LOSBlockedX = 0.0;\r\n\r\n'
    b'double LOSBlockedY = 0.0;\r\n\r\n'
    b'double LOSBlockedZ = 0.0;\r\n\r\n'
    b'if( algorithm.calculateLineOfSight(\r\n\r\n'
    b'LOSStartX, LOSStartY, LOSStartZ,\r\n\r\n'
    b'LOSEndX, LOSEndY, LOSEndZ,\r\n\r\n'
    b'LOSBlockedX, LOSBlockedY, LOSBlockedZ)\r\n\r\n'
    b'== TSLTerrainVSAlgorithmRFVS::LOSResultBlocked )\r\n\r\n'
    b'{\r\n\r\n'
    b'// The end point is not visible from the start point.\r\n\r\n'
    b'// The point where the line is blocked is stored in\r\n\r\n'
    b'// LOSBlockedX, LOSBlockedY, LOSBlockedZ\r\n\r\n'
    b'}\r\n\r\n'
    b'// The end point is visible from the start point.\r\n\r\n'
    b'// Release our references\r\n\r\n'
    b'input-\\>dec();\r\n\r\n'
    b'### Area Viewshed Using Provided Classes',
    b'### Single Point-to-point Line of Sight\r\n\r\n'
    b'```cpp\r\n'
    b'// Set up the input object, using the current display size, and extent\r\n\r\n'
    b'// The provided extent/display size will determine which level of detail\r\n\r\n'
    b'// is used within the terrain database.\r\n\r\n'
    b'TSLTerrainVSInputTerrainDatabase* input =\r\n\r\n'
    b'new TSLTerrainVSInputTerrainDatabase(&m_terrainDatabase,\r\n\r\n'
    b'displayExtent, displayWidth, displayHeight);\r\n\r\n'
    b'// Setup the viewshed algorithm\r\n\r\n'
    b'// For single LOS calculations, the RFVS algorithm doesn\'t require\r\n\r\n'
    b'// a compositor object.\r\n\r\n'
    b'// It does however require an input object, to calculate whether\r\n\r\n'
    b'// the line is blocked by terrain.\r\n\r\n'
    b'TSLTerrainVSAlgorithmRFVS algorithm(input, NULL);\r\n\r\n'
    b'// Determine whether the end point can be seen from the start point.\r\n\r\n'
    b'// If it cannot, the \'blocked\' point will be populated\r\n\r\n'
    b'double LOSStartX = -122.0;\r\n\r\n'
    b'double LOSStartY = 37.0;\r\n\r\n'
    b'double LOSStartZ = 100.0;\r\n\r\n'
    b'double LOSEndX = -121.5;\r\n\r\n'
    b'double LOSEndY = 37.35;\r\n\r\n'
    b'double LOSEndZ = 0.0; // Sea level\r\n\r\n'
    b'// Storage for the \'blocked\' point\r\n\r\n'
    b'double LOSBlockedX = 0.0;\r\n\r\n'
    b'double LOSBlockedY = 0.0;\r\n\r\n'
    b'double LOSBlockedZ = 0.0;\r\n\r\n'
    b'if( algorithm.calculateLineOfSight(\r\n\r\n'
    b'LOSStartX, LOSStartY, LOSStartZ,\r\n\r\n'
    b'LOSEndX, LOSEndY, LOSEndZ,\r\n\r\n'
    b'LOSBlockedX, LOSBlockedY, LOSBlockedZ)\r\n\r\n'
    b'== TSLTerrainVSAlgorithmRFVS::LOSResultBlocked )\r\n\r\n'
    b'{\r\n\r\n'
    b'// The end point is not visible from the start point.\r\n\r\n'
    b'// The point where the line is blocked is stored in\r\n\r\n'
    b'// LOSBlockedX, LOSBlockedY, LOSBlockedZ\r\n\r\n'
    b'}\r\n\r\n'
    b'// The end point is visible from the start point.\r\n\r\n'
    b'// Release our references\r\n\r\n'
    b'input->dec();\r\n'
    b'```\r\n\r\n'
    b'### Area Viewshed Using Provided Classes'
))

# Fix 13: Lines 885-955: Area Viewshed using provided classes
fixes.append(('Fix13 Area Viewshed provided classes',
    b'Note: As this example uses the generic compositor/output objects it is not the fastest method of performing a viewshed, nor the recommended approach for most applications. This approach should mainly be used when performance is not critical and the results do not need to be displayed immediately.\r\n\r\n'
    b'// Create an input object array, at the specified size/extent.\r\n\r\n'
    b'// Data should be populated from the application-specific source.\r\n\r\n'
    b'// 100 x 100 sample grid, covering -30.0,-60.0 to 30.0,60.0.\r\n\r\n'
    b'// The provided coordinate system is EPSG:4326 (A valid coordinate system must // be provided for viewshed calculations)\r\n\r\n'
    b'TSLTerrainVSInputArray\\* input = new TSLTerrainVSInputArray(\r\n\r\n'
    b'100, 100,\r\n\r\n'
    b'TSLMUExtent(-30.0, -60.0, 30.0, 60.0),\r\n\r\n'
    b'coordSys4326);\r\n\r\n'
    b'// Create an output object to store viewshed results.\r\n\r\n'
    b'// This object should be created with the same extent/size as the input object.\r\n\r\n'
    b'// The output may be re-used for multiple viewsheds, however this basic\r\n\r\n'
    b'// implementation only provides basic validation of the coordinates.\r\n\r\n'
    b'TSLTerrainVSOutput::dataItem defaultVal;\r\n\r\n'
    b'defaultVal.type = TSLTerrainVSOutput::typeTSLTerrainVSVisibility;\r\n\r\n'
    b'defaultVal.data.v = TSLTerrainVSVisibility::TSLTerrainVSNoData;\r\n\r\n'
    b'TSLTerrainVSOutputArray\\* output = new TSLTerrainVSOutputArray(\r\n\r\n'
    b'input-\\>width(), input-\\>height(),\r\n\r\n'
    b'input-\\>queryExtent(), defaultVal);\r\n\r\n'
    b'// Create a compositor object.\r\n\r\n'
    b'TSLTerrainVSCompositorVisibility\\* compositor =\r\n\r\n'
    b'new TSLTerrainVSCompositorVisibility(output);\r\n\r\n'
    b'// Create the algorithm object.\r\n\r\n'
    b'TSLTerrainVSAlgorithmRFVS algorithm(input, compositor);\r\n\r\n'
    b'// Perform a viewshed calculation.\r\n\r\n'
    b'// The format of the data, and interpretation of results is defined by the\r\n\r\n'
    b'// compositor object.\r\n\r\n'
    b'// In this case, the visibility of each point will be stored in the output\r\n\r\n'
    b'// array.\r\n\r\n'
    b'algorithm.calculateViewshed(\r\n\r\n'
    b'centerX, centerY,\r\n\r\n'
    b'startHeightOffset, startRelativeToGround,\r\n\r\n'
    b'maximumRadius, endHeightOffset, endRelativeToGround);\r\n\r\n'
    b'// Release our references\r\n\r\n'
    b'input-\\>dec();\r\n\r\n'
    b'compositor-\\>dec();\r\n\r\n'
    b'output-\\>dec();\r\n\r\n'
    b'### Performance Considerations',
    b'Note: As this example uses the generic compositor/output objects it is not the fastest method of performing a viewshed, nor the recommended approach for most applications. This approach should mainly be used when performance is not critical and the results do not need to be displayed immediately.\r\n\r\n'
    b'```cpp\r\n'
    b'// Create an input object array, at the specified size/extent.\r\n\r\n'
    b'// Data should be populated from the application-specific source.\r\n\r\n'
    b'// 100 x 100 sample grid, covering -30.0,-60.0 to 30.0,60.0.\r\n\r\n'
    b'// The provided coordinate system is EPSG:4326 (A valid coordinate system must // be provided for viewshed calculations)\r\n\r\n'
    b'TSLTerrainVSInputArray* input = new TSLTerrainVSInputArray(\r\n\r\n'
    b'100, 100,\r\n\r\n'
    b'TSLMUExtent(-30.0, -60.0, 30.0, 60.0),\r\n\r\n'
    b'coordSys4326);\r\n\r\n'
    b'// Create an output object to store viewshed results.\r\n\r\n'
    b'// This object should be created with the same extent/size as the input object.\r\n\r\n'
    b'// The output may be re-used for multiple viewsheds, however this basic\r\n\r\n'
    b'// implementation only provides basic validation of the coordinates.\r\n\r\n'
    b'TSLTerrainVSOutput::dataItem defaultVal;\r\n\r\n'
    b'defaultVal.type = TSLTerrainVSOutput::typeTSLTerrainVSVisibility;\r\n\r\n'
    b'defaultVal.data.v = TSLTerrainVSVisibility::TSLTerrainVSNoData;\r\n\r\n'
    b'TSLTerrainVSOutputArray* output = new TSLTerrainVSOutputArray(\r\n\r\n'
    b'input->width(), input->height(),\r\n\r\n'
    b'input->queryExtent(), defaultVal);\r\n\r\n'
    b'// Create a compositor object.\r\n\r\n'
    b'TSLTerrainVSCompositorVisibility* compositor =\r\n\r\n'
    b'new TSLTerrainVSCompositorVisibility(output);\r\n\r\n'
    b'// Create the algorithm object.\r\n\r\n'
    b'TSLTerrainVSAlgorithmRFVS algorithm(input, compositor);\r\n\r\n'
    b'// Perform a viewshed calculation.\r\n\r\n'
    b'// The format of the data, and interpretation of results is defined by the\r\n\r\n'
    b'// compositor object.\r\n\r\n'
    b'// In this case, the visibility of each point will be stored in the output\r\n\r\n'
    b'// array.\r\n\r\n'
    b'algorithm.calculateViewshed(\r\n\r\n'
    b'centerX, centerY,\r\n\r\n'
    b'startHeightOffset, startRelativeToGround,\r\n\r\n'
    b'maximumRadius, endHeightOffset, endRelativeToGround);\r\n\r\n'
    b'// Release our references\r\n\r\n'
    b'input->dec();\r\n\r\n'
    b'compositor->dec();\r\n\r\n'
    b'output->dec();\r\n'
    b'```\r\n\r\n'
    b'### Performance Considerations'
))

# Apply all fixes
result = content
for name, old, new in fixes:
    if old in result:
        result = result.replace(old, new, 1)
        print(f'{name}: found=True')
    else:
        print(f'{name}: found=False')

with open(r'c:\maplink\maplink-docs\pages\developers-guide\terrain-sdk.md', 'wb') as f:
    f.write(result)

print('Done.')
