"""Fix bare code blocks in geometry-and-overlays.md"""

with open(r'c:\maplink\maplink-docs\pages\developers-guide\geometry-and-overlays.md', 'rb') as f:
    content = f.read()

fixes = []

# Fix G1: Bare geodetic polyline code block
fixes.append(('G1 geodetic polyline',
    b'Geodetic polylines are created in a very similar way to standard polylines:\r\n\r\n'
    b'TSLStandardDataLayer\\* stdLayer = \\...;\r\n\r\n'
    b'TSLDataLayer\\* mapLayer = \\...;\r\n\r\n'
    b'TSLCoordSet\\* cs = new TSLCoordSet;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(51.4775, -0.461389, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(40.08, 116.584444, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'TSLGeodeticPolyline\\* polyline = stdLayer-\\>entitySet()-\\>\r\n\r\n'
    b'createGeodeticPolyline( 0, cs, true ) ;\r\n\r\n'
    b'if ( !polyline )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'polyline-\\>setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'polyline-\\>setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'polyline-\\>setRendering( TSLRenderingAttributeEdgeThickness, 6 ) ;\r\n\r\n'
    b'Geodetic polylines can also be created directly with TSLGeodeticPolyline::create.',
    b'Geodetic polylines are created in a very similar way to standard polylines:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLStandardDataLayer* stdLayer = ...;\r\n\r\n'
    b'TSLDataLayer* mapLayer = ...;\r\n\r\n'
    b'TSLCoordSet* cs = new TSLCoordSet;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(51.4775, -0.461389, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(40.08, 116.584444, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'TSLGeodeticPolyline* polyline = stdLayer->entitySet()->\r\n\r\n'
    b'createGeodeticPolyline( 0, cs, true ) ;\r\n\r\n'
    b'if ( !polyline )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'polyline->setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'polyline->setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'polyline->setRendering( TSLRenderingAttributeEdgeThickness, 6 ) ;\r\n'
    b'```\r\n\r\n'
    b'Geodetic polylines can also be created directly with TSLGeodeticPolyline::create.'
))

# Fix G2: Bare geodetic polygon code block (note stray \] at end)
fixes.append(('G2 geodetic polygon',
    b'Geodetic polygons are created in a very similar way to standard polygons:\r\n\r\n'
    b'TSLStandardDataLayer\\* stdLayer = \\...;\r\n\r\n'
    b'TSLDataLayer\\* mapLayer = \\...;\r\n\r\n'
    b'TSLCoordSet\\* cs = new TSLCoordSet;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(20.0, 10.0, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(40.0, 0.0, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(30.0, -20.0, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(70.0, 20.0, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'cs-\\>add(x, y);\r\n\r\n'
    b'TSLGeodeticPolygon\\* polygon = stdLayer-\\>entitySet()-\\>\r\n\r\n'
    b'createGeodeticPolygon( 0, cs, true ) ;\r\n\r\n'
    b'if (!polygon)\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'polygon-\\>setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'polygon-\\>setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'polygon-\\>setRendering( TSLRenderingAttributeEdgeThickness, 2 ) ;\r\n\r\n'
    b'polygon-\\>setRendering( TSLRenderingAttributeFillStyle, 502 ) ;\r\n\r\n'
    b'polygon-\\>setRendering( TSLRenderingAttributeFillColour,\r\n\r\n'
    b'TSLComposeRGB(255,128,255) ) ;\\]\r\n\r\n'
    b'Geodetic polygons can also be created directly with TSLGeodeticPolygon::create.',
    b'Geodetic polygons are created in a very similar way to standard polygons:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLStandardDataLayer* stdLayer = ...;\r\n\r\n'
    b'TSLDataLayer* mapLayer = ...;\r\n\r\n'
    b'TSLCoordSet* cs = new TSLCoordSet;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(20.0, 10.0, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(40.0, 0.0, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(30.0, -20.0, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(70.0, 20.0, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'cs->add(x, y);\r\n\r\n'
    b'TSLGeodeticPolygon* polygon = stdLayer->entitySet()->\r\n\r\n'
    b'createGeodeticPolygon( 0, cs, true ) ;\r\n\r\n'
    b'if (!polygon)\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'polygon->setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'polygon->setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'polygon->setRendering( TSLRenderingAttributeEdgeThickness, 2 ) ;\r\n\r\n'
    b'polygon->setRendering( TSLRenderingAttributeFillStyle, 502 ) ;\r\n\r\n'
    b'polygon->setRendering( TSLRenderingAttributeFillColour,\r\n\r\n'
    b'TSLComposeRGB(255,128,255) ) ;\r\n'
    b'```\r\n\r\n'
    b'Geodetic polygons can also be created directly with TSLGeodeticPolygon::create.'
))

# Fix G3: Bare geodetic ellipse code block
fixes.append(('G3 geodetic ellipse',
    b'Geodetic ellipses are created in a similar way to standard ellipses, except for the radii:\r\n\r\n'
    b'TSLStandardDataLayer\\* stdLayer = \\...;\r\n\r\n'
    b'TSLDataLayer\\* mapLayer = \\...;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(51.5, 0.05, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'TSLGeodeticEllipse\\* ellipse = stdLayer-\\>entitySet()-\\>\r\n\r\n'
    b'createGeodeticEllipse( 0, x, y,\r\n\r\n'
    b'1000000.0, 2000000.0, M_PI/4.0 );\r\n\r\n'
    b'if (!ellipse)\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'ellipse-\\>setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'ellipse-\\>setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'ellipse-\\>setRendering( TSLRenderingAttributeEdgeThickness, 2 ) ;\r\n\r\n'
    b'ellipse-\\>setRendering( TSLRenderingAttributeFillStyle, 502 ) ;\r\n\r\n'
    b'ellipse-\\>setRendering( TSLRenderingAttributeFillColour,\r\n\r\n'
    b'TSLComposeRGB(255,128,255) ) ;\r\n\r\n'
    b'Geodetic ellipses can also be created directly with TSLGeodeticEllipse::create.',
    b'Geodetic ellipses are created in a similar way to standard ellipses, except for the radii:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLStandardDataLayer* stdLayer = ...;\r\n\r\n'
    b'TSLDataLayer* mapLayer = ...;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(51.5, 0.05, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'TSLGeodeticEllipse* ellipse = stdLayer->entitySet()->\r\n\r\n'
    b'createGeodeticEllipse( 0, x, y,\r\n\r\n'
    b'1000000.0, 2000000.0, M_PI/4.0 );\r\n\r\n'
    b'if (!ellipse)\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'ellipse->setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'ellipse->setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'ellipse->setRendering( TSLRenderingAttributeEdgeThickness, 2 ) ;\r\n\r\n'
    b'ellipse->setRendering( TSLRenderingAttributeFillStyle, 502 ) ;\r\n\r\n'
    b'ellipse->setRendering( TSLRenderingAttributeFillColour,\r\n\r\n'
    b'TSLComposeRGB(255,128,255) ) ;\r\n'
    b'```\r\n\r\n'
    b'Geodetic ellipses can also be created directly with TSLGeodeticEllipse::create.'
))

# Fix G4: Bare geodetic arc code block
fixes.append(('G4 geodetic arc',
    b'Geodetic arcs are created in a similar way to standard arcs, except for the radii:\r\n\r\n'
    b'TSLStandardDataLayer\\* stdLayer = \\...;\r\n\r\n'
    b'TSLDataLayer\\* mapLayer = \\...;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer-\\>latLongToTMC(51.5, 0.05, &x, &y) )\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'TSLGeodeticArc\\* arc = stdLayer-\\>entitySet()-\\>\r\n\r\n'
    b'createGeodeticArc( 0, M_PI/2, 2\\*M_PI, x, y,\r\n\r\n'
    b'1000000.0, 2000000.0, M_PI/4.0 );\r\n\r\n'
    b'if (!arc)\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'arc-\\>setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'arc-\\>setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'arc-\\>setRendering( TSLRenderingAttributeEdgeThickness, 4 ) ;\r\n\r\n'
    b'Geodetic arcs can also be created directly with TSLGeodeticArc::create.',
    b'Geodetic arcs are created in a similar way to standard arcs, except for the radii:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLStandardDataLayer* stdLayer = ...;\r\n\r\n'
    b'TSLDataLayer* mapLayer = ...;\r\n\r\n'
    b'TSLTMC x, y;\r\n\r\n'
    b'if ( !mapLayer->latLongToTMC(51.5, 0.05, &x, &y) )\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'TSLGeodeticArc* arc = stdLayer->entitySet()->\r\n\r\n'
    b'createGeodeticArc( 0, M_PI/2, 2*M_PI, x, y,\r\n\r\n'
    b'1000000.0, 2000000.0, M_PI/4.0 );\r\n\r\n'
    b'if (!arc)\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'arc->setRendering( TSLRenderingAttributeEdgeStyle, 1 ) ;\r\n\r\n'
    b'arc->setRendering( TSLRenderingAttributeEdgeColour,\r\n\r\n'
    b'TSLComposeRGB(255,0,255) ) ;\r\n\r\n'
    b'arc->setRendering( TSLRenderingAttributeEdgeThickness, 4 ) ;\r\n'
    b'```\r\n\r\n'
    b'Geodetic arcs can also be created directly with TSLGeodeticArc::create.'
))

# Fix G5: Bare user geometry create/destroy code
fixes.append(('G5 user geometry create/destroy',
    b'Creating and destroying user geometry:\r\n\r\n'
    b'TSLStandardDataLayer\\* stdLayer = \\...;\r\n\r\n'
    b'TSLClientUserGeometryEntity\\* client = new \\...;\r\n\r\n'
    b'TSLUserGeometryEntity\\* entity = stdLayer-\\>entitySet()-\\>\r\n\r\n'
    b'createUserGeometry(client, false);\r\n\r\n'
    b'if (!entity)\r\n\r\n'
    b'\\... // handle error\r\n\r\n'
    b'\\...\r\n\r\n'
    b'entity-\\>destroy();\r\n\r\n'
    b'delete client; // don\'t need this if ownsClient is true\r\n\r\n'
    b'### TSLClientUserGeometryEntity',
    b'Creating and destroying user geometry:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLStandardDataLayer* stdLayer = ...;\r\n\r\n'
    b'TSLClientUserGeometryEntity* client = new ...;\r\n\r\n'
    b'TSLUserGeometryEntity* entity = stdLayer->entitySet()->\r\n\r\n'
    b'createUserGeometry(client, false);\r\n\r\n'
    b'if (!entity)\r\n\r\n'
    b'... // handle error\r\n\r\n'
    b'...\r\n\r\n'
    b'entity->destroy();\r\n\r\n'
    b'delete client; // don\'t need this if ownsClient is true\r\n'
    b'```\r\n\r\n'
    b'### TSLClientUserGeometryEntity'
))

# Fix G6: Bare RectangleClient class definition
fixes.append(('G6 RectangleClient class',
    b'Here is an example partial implementation of a user geometry client:\r\n\r\n'
    b'class RectangleClient : public TSLClientUserGeometryEntity\r\n\r\n'
    b'{\r\n\r\n'
    b'private:\r\n\r\n'
    b'TSLEnvelope m_extent;\r\n\r\n'
    b'public:\r\n\r\n'
    b'// Constructor\r\n\r\n'
    b'RectangleClient(TSLTMC left, TSLTMC bottom, TSLTMC right, TSLTMC top)\r\n\r\n'
    b'{\r\n\r\n'
    b'm_extent.corners( left, bottom, right, top ); // bounding box\r\n\r\n'
    b'}\r\n\r\n'
    b'// Destructor\r\n\r\n'
    b'virtual \\~RectangleClient()\r\n\r\n'
    b'{\r\n\r\n'
    b'}\r\n\r\n'
    b'// Draw a rectangle using rendering interface\r\n\r\n'
    b'virtual bool draw(int uniqueSurfaceID,\r\n\r\n'
    b'TSLRenderingInterface\\* renderingInterface,\r\n\r\n'
    b'const TSLEnvelope& extent, TSLRenderLevel renderLevel,\r\n\r\n'
    b'double screenResolution)\r\n\r\n'
    b'{\r\n\r\n'
    b'const int blue = TSLDrawingSurface::getIDOfNearestColour(0,0,255);\r\n\r\n'
    b'// Construct a rectangle\r\n\r\n'
    b'TSLCoord coords\\[4\\]; // bottom left, top left, top right, bottom right\r\n\r\n'
    b'coords\\[0\\] = m_extent.bottomLeft();\r\n\r\n'
    b'coords\\[1\\] = TSLCoord( m_extent.bottomLeft().x(), m_extent.topRight().y() );\r\n\r\n'
    b'coords\\[2\\] = m_extent.topRight();\r\n\r\n'
    b'coords\\[3\\] = TSLCoord( m_extent.topRight().x(), m_extent.bottomLeft().y() );\r\n\r\n'
    b'// Set up rendering attributes - translucent rectangle\r\n\r\n'
    b'renderingInterface-\\>setupEdgeAttributes( -1, 0, 0.0 );\r\n\r\n'
    b'renderingInterface-\\>setupAreaAttributes( 503, blue );\r\n\r\n'
    b'// Attempt to draw rectangle, return false if fails\r\n\r\n'
    b'return renderingInterface-\\>drawPolygon(coords, \\_countof(coords));\r\n\r\n'
    b'}\r\n\r\n'
    b'// Save the rectangle\r\n\r\n'
    b'virtual int save(TSLofstream\\& stream)\r\n\r\n'
    b'{\r\n\r\n'
    b'// Stream out data\r\n\r\n'
    b'\\...\r\n\r\n'
    b'return RECTANGLE_USER_GEOMETRY_ID; // unique ID of the user geometry type\r\n\r\n'
    b'}\r\n\r\n'
    b'// Return the envelope for this rectangle\r\n\r\n'
    b'virtual TSLEnvelope envelope(int uniqueSurfaceID)\r\n\r\n'
    b'{\r\n\r\n'
    b'return m_extent;\r\n\r\n'
    b'}\r\n\r\n'
    b'};\r\n\r\n'
    b'### Loading and saving user geometry',
    b'Here is an example partial implementation of a user geometry client:\r\n\r\n'
    b'```cpp\r\n'
    b'class RectangleClient : public TSLClientUserGeometryEntity\r\n\r\n'
    b'{\r\n\r\n'
    b'private:\r\n\r\n'
    b'TSLEnvelope m_extent;\r\n\r\n'
    b'public:\r\n\r\n'
    b'// Constructor\r\n\r\n'
    b'RectangleClient(TSLTMC left, TSLTMC bottom, TSLTMC right, TSLTMC top)\r\n\r\n'
    b'{\r\n\r\n'
    b'm_extent.corners( left, bottom, right, top ); // bounding box\r\n\r\n'
    b'}\r\n\r\n'
    b'// Destructor\r\n\r\n'
    b'virtual ~RectangleClient()\r\n\r\n'
    b'{\r\n\r\n'
    b'}\r\n\r\n'
    b'// Draw a rectangle using rendering interface\r\n\r\n'
    b'virtual bool draw(int uniqueSurfaceID,\r\n\r\n'
    b'TSLRenderingInterface* renderingInterface,\r\n\r\n'
    b'const TSLEnvelope& extent, TSLRenderLevel renderLevel,\r\n\r\n'
    b'double screenResolution)\r\n\r\n'
    b'{\r\n\r\n'
    b'const int blue = TSLDrawingSurface::getIDOfNearestColour(0,0,255);\r\n\r\n'
    b'// Construct a rectangle\r\n\r\n'
    b'TSLCoord coords[4]; // bottom left, top left, top right, bottom right\r\n\r\n'
    b'coords[0] = m_extent.bottomLeft();\r\n\r\n'
    b'coords[1] = TSLCoord( m_extent.bottomLeft().x(), m_extent.topRight().y() );\r\n\r\n'
    b'coords[2] = m_extent.topRight();\r\n\r\n'
    b'coords[3] = TSLCoord( m_extent.topRight().x(), m_extent.bottomLeft().y() );\r\n\r\n'
    b'// Set up rendering attributes - translucent rectangle\r\n\r\n'
    b'renderingInterface->setupEdgeAttributes( -1, 0, 0.0 );\r\n\r\n'
    b'renderingInterface->setupAreaAttributes( 503, blue );\r\n\r\n'
    b'// Attempt to draw rectangle, return false if fails\r\n\r\n'
    b'return renderingInterface->drawPolygon(coords, _countof(coords));\r\n\r\n'
    b'}\r\n\r\n'
    b'// Save the rectangle\r\n\r\n'
    b'virtual int save(TSLofstream& stream)\r\n\r\n'
    b'{\r\n\r\n'
    b'// Stream out data\r\n\r\n'
    b'...\r\n\r\n'
    b'return RECTANGLE_USER_GEOMETRY_ID; // unique ID of the user geometry type\r\n\r\n'
    b'}\r\n\r\n'
    b'// Return the envelope for this rectangle\r\n\r\n'
    b'virtual TSLEnvelope envelope(int uniqueSurfaceID)\r\n\r\n'
    b'{\r\n\r\n'
    b'return m_extent;\r\n\r\n'
    b'}\r\n\r\n'
    b'};\r\n'
    b'```\r\n\r\n'
    b'### Loading and saving user geometry'
))

# Fix G7: Bare load callback registration call
fixes.append(('G7 load callback registration',
    b'Setting a load callback function:\r\n\r\n'
    b'TSLUserGeometryEntity::\r\n\r\n'
    b'registerUserGeometryClientLoadCallback(loadUserGeometryCallback);\r\n\r\n'
    b'Here is a skeleton load callback function:',
    b'Setting a load callback function:\r\n\r\n'
    b'```cpp\r\n'
    b'TSLUserGeometryEntity::\r\n\r\n'
    b'registerUserGeometryClientLoadCallback(loadUserGeometryCallback);\r\n'
    b'```\r\n\r\n'
    b'Here is a skeleton load callback function:'
))

# Fix G8: Bare load callback function skeleton
fixes.append(('G8 load callback function',
    b'Here is a skeleton load callback function:\r\n\r\n'
    b'static TSLClientUserGeometryEntity\\* loadUserGeometryCallback(\r\n\r\n'
    b'TSLifstream\\& stream,\r\n\r\n'
    b'int userGeometryID,\r\n\r\n'
    b'bool\\& assumeOwnership)\r\n\r\n'
    b'{\r\n\r\n'
    b'// whether returned entities will be freed by MapLink:\r\n\r\n'
    b'assumeOwnership = \\...;\r\n\r\n'
    b'switch (userGeometryID)\r\n\r\n'
    b'{\r\n\r\n'
    b'case RECTANGLE_USER_GEOMETRY_ID:\r\n\r\n'
    b'\\... // stream in client and return it\r\n\r\n'
    b'\\... // etc\r\n\r\n'
    b'default:\r\n\r\n'
    b'return NULL;\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'## Data Layers',
    b'Here is a skeleton load callback function:\r\n\r\n'
    b'```cpp\r\n'
    b'static TSLClientUserGeometryEntity* loadUserGeometryCallback(\r\n\r\n'
    b'TSLifstream& stream,\r\n\r\n'
    b'int userGeometryID,\r\n\r\n'
    b'bool& assumeOwnership)\r\n\r\n'
    b'{\r\n\r\n'
    b'// whether returned entities will be freed by MapLink:\r\n\r\n'
    b'assumeOwnership = ...;\r\n\r\n'
    b'switch (userGeometryID)\r\n\r\n'
    b'{\r\n\r\n'
    b'case RECTANGLE_USER_GEOMETRY_ID:\r\n\r\n'
    b'... // stream in client and return it\r\n\r\n'
    b'... // etc\r\n\r\n'
    b'default:\r\n\r\n'
    b'return NULL;\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'## Data Layers'
))

# Fix G9a: Bare MGRS create layer (2 lines before existing blockquote)
fixes.append(('G9a MGRS create layer',
    b'> To create an MGRS Grid Data Layer:\r\n\r\n'
    b'm_mgrsGridLayer = new TSLMGRSGridDataLayer ;\r\n\r\n'
    b'm_mgrsGridLayer-\\>setMapDataLayer(m_mapDataLayer);\r\n\r\n'
    b'> To initialise the MGRS grid line styles:',
    b'> To create an MGRS Grid Data Layer:\r\n\r\n'
    b'```cpp\r\n'
    b'm_mgrsGridLayer = new TSLMGRSGridDataLayer ;\r\n\r\n'
    b'm_mgrsGridLayer->setMapDataLayer(m_mapDataLayer);\r\n'
    b'```\r\n\r\n'
    b'> To initialise the MGRS grid line styles:'
))

# Fix G9b: Merge bare lookupProfile code with existing ```cpp fence, and fix "To initialise" text inside fence
# The bare code runs from after "> To initialise..." through the existing ```cpp fence
# then "To initialise the MGRS grid text styles:" is wrongly inside the fence
fixes.append(('G9b MGRS lookupProfile merge with fence',
    b'long utm1kmC, utm1kmS, utm1kmT ;\r\n\r\n'
    b'long utm10kmC, utm10kmS, utm10kmT ;\r\n\r\n'
    b'long utm100kmC, utm100kmS, utm100kmT ;\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmColour",&utm1kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,127" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmColour",&utm10kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,192" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmColour",&utm100kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,255" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmStyle",&utm1kmS, 6 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmStyle",&utm10kmS, 3 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmStyle",&utm100kmS, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmThickness",&utm1kmT, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmThickness",&utm10kmT, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmThickness",&utm100kmT, 2);\r\n\r\n'
    b'```cpp\r\n',
    b'```cpp\r\n'
    b'long utm1kmC, utm1kmS, utm1kmT ;\r\n\r\n'
    b'long utm10kmC, utm10kmS, utm10kmT ;\r\n\r\n'
    b'long utm100kmC, utm100kmS, utm100kmT ;\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmColour",&utm1kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,127" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmColour",&utm10kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,192" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmColour",&utm100kmC,\r\n\r\n'
    b'getIDOfNearestColour( "0,0,255" ) );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmStyle",&utm1kmS, 6 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmStyle",&utm10kmS, 3 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmStyle",&utm100kmS, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm1kmThickness",&utm1kmT, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm10kmThickness",&utm10kmT, 1 );\r\n\r\n'
    b'TSLProfileHelper::lookupProfile("gridUtm100kmThickness",&utm100kmT, 2);\r\n\r\n'
))

# Fix G9c: Extract "To initialise the MGRS grid text styles:" from inside fence
fixes.append(('G9c MGRS text styles label out of fence',
    b'(double)utm100kmT);\r\n\r\nTo initialise the MGRS grid text styles:\r\n```',
    b'(double)utm100kmT);\r\n```\r\n\r\nTo initialise the MGRS grid text styles:'
))

# Fix G9d: Bare initialiseLabel calls after fence closes
fixes.append(('G9d MGRS initialiseLabel calls',
    b'initialiseLabel(m_mgrsGridLayer, "mgrsLabel );\r\n\r\n'
    b'initialiseLabel(m_mgrsGridLayer, "gridLineLabel );\r\n\r\n'
    b'> Where the method initialiseLabel sets the following attributes for the text:',
    b'```cpp\r\n'
    b'initialiseLabel(m_mgrsGridLayer, "mgrsLabel");\r\n\r\n'
    b'initialiseLabel(m_mgrsGridLayer, "gridLineLabel");\r\n'
    b'```\r\n\r\n'
    b'> Where the method initialiseLabel sets the following attributes for the text:'
))

# Fix G9e: Bare surface->addDataLayer and setDataLayerProps
fixes.append(('G9e MGRS addDataLayer',
    b'> Add the TSLMGRSGridDataLayer to the surface and set its visibility.\r\n\r\n'
    b'surface-\\>addDataLayer( m_mgrsGridLayer, m_mgrsGridLayerName ) ;\r\n\r\n'
    b'surface-\\>setDataLayerProps( m_mgrsGridLayerName, TSLPropertyVisible,\r\n\r\n'
    b'm_mgrsGridLayerVisible ) ;\r\n\r\n'
    b'> To set the "single zone" mode:',
    b'> Add the TSLMGRSGridDataLayer to the surface and set its visibility.\r\n\r\n'
    b'```cpp\r\n'
    b'surface->addDataLayer( m_mgrsGridLayer, m_mgrsGridLayerName ) ;\r\n\r\n'
    b'surface->setDataLayerProps( m_mgrsGridLayerName, TSLPropertyVisible,\r\n\r\n'
    b'm_mgrsGridLayerVisible ) ;\r\n'
    b'```\r\n\r\n'
    b'> To set the "single zone" mode:'
))

# Fix G9f: Bare setZone calls
fixes.append(('G9f MGRS setZone calls',
    b'> To set the "single zone" mode:\r\n\r\n'
    b'm_mgrsGridLayer-\\>setZone(zone, band);\r\n\r\n'
    b'> and back to "automatic" mode:\r\n\r\n'
    b'm_mgrsGridLayer-\\>setZone(-1, 0);\r\n\r\n'
    b'### The TSLLatLongGridDataLayer',
    b'> To set the "single zone" mode:\r\n\r\n'
    b'```cpp\r\n'
    b'm_mgrsGridLayer->setZone(zone, band);\r\n'
    b'```\r\n\r\n'
    b'> and back to "automatic" mode:\r\n\r\n'
    b'```cpp\r\n'
    b'm_mgrsGridLayer->setZone(-1, 0);\r\n'
    b'```\r\n\r\n'
    b'### The TSLLatLongGridDataLayer'
))

# Fix G9g: Bare TSLLatLongGridDataLayer create/ticks calls
fixes.append(('G9g LatLong create/ticks',
    b'> To create the TSLLatLongGridDataLayer:\r\n\r\n'
    b'm_latLonGridLayer = new TSLLatLongGridDataLayer ;\r\n\r\n'
    b'm_latLonGridLayer-\\>setMapDataLayer(m_mapDataLayer);\r\n\r\n'
    b'> To enable ticks on the grid lines showing divisions:\r\n\r\n'
    b'm_latLonGridLayer-\\>ticks(true);\r\n\r\n'
    b'### The TSLGARSGridDataLayer',
    b'> To create the TSLLatLongGridDataLayer:\r\n\r\n'
    b'```cpp\r\n'
    b'm_latLonGridLayer = new TSLLatLongGridDataLayer ;\r\n\r\n'
    b'm_latLonGridLayer->setMapDataLayer(m_mapDataLayer);\r\n'
    b'```\r\n\r\n'
    b'> To enable ticks on the grid lines showing divisions:\r\n\r\n'
    b'```cpp\r\n'
    b'm_latLonGridLayer->ticks(true);\r\n'
    b'```\r\n\r\n'
    b'### The TSLGARSGridDataLayer'
))

# Fix G10a: Pseudo-code fence inversion for text size calculation
# ```cpp wraps description; pseudo-code is bare outside
fixes.append(('G10a text size pseudo-code fence inversion',
    b'```cpp\r\nThe size of the font used to render the text is calculated using the following pseudo-code:\r\n```\r\n\r\n'
    b'if ( obsolete fixed size flag is true )\r\n\r\n'
    b'{\r\n\r\n'
    b'sizeInPixels = Entity size\r\n\r\n'
    b'}\r\n\r\n'
    b'else\r\n\r\n'
    b'{\r\n\r\n'
    b'switch ( textSizeFactorUnits )\r\n\r\n'
    b'{\r\n\r\n'
    b'case pixels :\r\n\r\n'
    b'sizeInPixels = size factor\r\n\r\n'
    b'case map units :\r\n\r\n'
    b'sizeInPixels = (size factor \\* tmcPerMU) / tmcPerDU\r\n\r\n'
    b'case scale factor :\r\n\r\n'
    b'sizeInPixels = (Entity size \\* size factor ) / tmcPerDU\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( sizeInPixels \\< minHeight )\r\n\r\n'
    b'sizeInPixels = minHeight ;\r\n\r\n'
    b'else if ( sizeInPixels \\> maxHeight )\r\n\r\n'
    b'sizeInPixels = maxHeight ;\r\n\r\n'
    b'### Symbol Rendering Attributes',
    b'The size of the font used to render the text is calculated using the following pseudo-code:\r\n\r\n'
    b'```\r\n'
    b'if ( obsolete fixed size flag is true )\r\n\r\n'
    b'{\r\n\r\n'
    b'sizeInPixels = Entity size\r\n\r\n'
    b'}\r\n\r\n'
    b'else\r\n\r\n'
    b'{\r\n\r\n'
    b'switch ( textSizeFactorUnits )\r\n\r\n'
    b'{\r\n\r\n'
    b'case pixels :\r\n\r\n'
    b'sizeInPixels = size factor\r\n\r\n'
    b'case map units :\r\n\r\n'
    b'sizeInPixels = (size factor * tmcPerMU) / tmcPerDU\r\n\r\n'
    b'case scale factor :\r\n\r\n'
    b'sizeInPixels = (Entity size * size factor ) / tmcPerDU\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( sizeInPixels < minHeight )\r\n\r\n'
    b'sizeInPixels = minHeight ;\r\n\r\n'
    b'else if ( sizeInPixels > maxHeight )\r\n\r\n'
    b'sizeInPixels = maxHeight ;\r\n'
    b'```\r\n\r\n'
    b'### Symbol Rendering Attributes'
))

# Fix G10b: Pseudo-code fence inversion for symbol size calculation
fixes.append(('G10b symbol size pseudo-code fence inversion',
    b'```cpp\r\nThe size of the symbol used to render the text is calculated using the following pseudo-code:\r\n```\r\n\r\n'
    b'if ( obsolete fixed size flag is true )\r\n\r\n'
    b'{\r\n\r\n'
    b'sizeInPixels = Entity size\r\n\r\n'
    b'}\r\n\r\n'
    b'else\r\n\r\n'
    b'{\r\n\r\n'
    b'switch ( symbolSizeFactorUnits )\r\n\r\n'
    b'{\r\n\r\n'
    b'case pixels :\r\n\r\n'
    b'sizeInPixels = size factor\r\n\r\n'
    b'case map units :\r\n\r\n'
    b'sizeInPixels = (size factor \\* tmcPerMU) / tmcPerDU\r\n\r\n'
    b'case scale factor :\r\n\r\n'
    b'sizeInPixels = (Entity size \\* size factor ) / tmcPerDU\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( sizeInPixels \\< minHeight )\r\n\r\n'
    b'sizeInPixels = minHeight ;\r\n\r\n'
    b'else if ( sizeInPixels \\> maxHeight )\r\n\r\n'
    b'sizeInPixels = maxHeight ;\r\n\r\n'
    b'### Raster Icon Symbols',
    b'The size of the symbol used to render the text is calculated using the following pseudo-code:\r\n\r\n'
    b'```\r\n'
    b'if ( obsolete fixed size flag is true )\r\n\r\n'
    b'{\r\n\r\n'
    b'sizeInPixels = Entity size\r\n\r\n'
    b'}\r\n\r\n'
    b'else\r\n\r\n'
    b'{\r\n\r\n'
    b'switch ( symbolSizeFactorUnits )\r\n\r\n'
    b'{\r\n\r\n'
    b'case pixels :\r\n\r\n'
    b'sizeInPixels = size factor\r\n\r\n'
    b'case map units :\r\n\r\n'
    b'sizeInPixels = (size factor * tmcPerMU) / tmcPerDU\r\n\r\n'
    b'case scale factor :\r\n\r\n'
    b'sizeInPixels = (Entity size * size factor ) / tmcPerDU\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'if ( sizeInPixels < minHeight )\r\n\r\n'
    b'sizeInPixels = minHeight ;\r\n\r\n'
    b'else if ( sizeInPixels > maxHeight )\r\n\r\n'
    b'sizeInPixels = maxHeight ;\r\n'
    b'```\r\n\r\n'
    b'### Raster Icon Symbols'
))

for name, old, new in fixes:
    found = old in content
    print(f'{name}: found={found}')
    if found:
        content = content.replace(old, new, 1)
    else:
        # Try to find partial match to help debug
        # check first 60 bytes
        snippet = old[:60]
        snippet_found = snippet in content
        print(f'  -> first 60 bytes found: {snippet_found}')

with open(r'c:\maplink\maplink-docs\pages\developers-guide\geometry-and-overlays.md', 'wb') as f:
    f.write(content)
print('geometry-and-overlays.md written')
