"""Fix remaining G6 and G8 patterns (unescaped & in TSLofstream/TSLifstream)"""

with open(r'c:\maplink\maplink-docs\pages\developers-guide\geometry-and-overlays.md', 'rb') as f:
    content = f.read()

fixes = []

# Fix G6: RectangleClient class - & is NOT escaped before TSLofstream/TSLEnvelope
fixes.append(('G6 RectangleClient class',
    b'Here is an example partial implementation of a user geometry client:\r\n\r\n'
    b'class RectangleClient : public TSLClientUserGeometryEntity\r\n\r\n'
    b'{\r\n\r\n'
    b'private:\r\n\r\n'
    b'TSLEnvelope m_extent;\r\n\r\n'
    b'public:\r\n\r\n'
    b'// Constructor\r\n\r\n'
    b'RectangleClient(TSLTMC left, TSLTMC bottom, TSLTMC right, TSLTMC top)\r\n\r\n'
    b'{\r\n\r\n'
    b'm_extent.corners( left, bottom, right, top ); // bounding box\r\n\r\n'
    b'}\r\n\r\n'
    b'// Destructor\r\n\r\n'
    b'virtual \\~RectangleClient()\r\n\r\n'
    b'{\r\n\r\n'
    b'}\r\n\r\n'
    b'// Draw a rectangle using rendering interface\r\n\r\n'
    b'virtual bool draw(int uniqueSurfaceID,\r\n\r\n'
    b'TSLRenderingInterface\\* renderingInterface,\r\n\r\n'
    b'const TSLEnvelope& extent, TSLRenderLevel renderLevel,\r\n\r\n'
    b'double screenResolution)\r\n\r\n'
    b'{\r\n\r\n'
    b'const int blue = TSLDrawingSurface::getIDOfNearestColour(0,0,255);\r\n\r\n'
    b'// Construct a rectangle\r\n\r\n'
    b'TSLCoord coords\\[4\\]; // bottom left, top left, top right, bottom right\r\n\r\n'
    b'coords\\[0\\] = m_extent.bottomLeft();\r\n\r\n'
    b'coords\\[1\\] = TSLCoord( m_extent.bottomLeft().x(), m_extent.topRight().y() );\r\n\r\n'
    b'coords\\[2\\] = m_extent.topRight();\r\n\r\n'
    b'coords\\[3\\] = TSLCoord( m_extent.topRight().x(), m_extent.bottomLeft().y() );\r\n\r\n'
    b'// Set up rendering attributes - translucent rectangle\r\n\r\n'
    b'renderingInterface-\\>setupEdgeAttributes( -1, 0, 0.0 );\r\n\r\n'
    b'renderingInterface-\\>setupAreaAttributes( 503, blue );\r\n\r\n'
    b'// Attempt to draw rectangle, return false if fails\r\n\r\n'
    b'return renderingInterface-\\>drawPolygon(coords, \\_countof(coords));\r\n\r\n'
    b'}\r\n\r\n'
    b'// Save the rectangle\r\n\r\n'
    b'virtual int save(TSLofstream& stream)\r\n\r\n'
    b'{\r\n\r\n'
    b'// Stream out data\r\n\r\n'
    b'\\...\r\n\r\n'
    b'return RECTANGLE_USER_GEOMETRY_ID; // unique ID of the user geometry type\r\n\r\n'
    b'}\r\n\r\n'
    b'// Return the envelope for this rectangle\r\n\r\n'
    b'virtual TSLEnvelope envelope(int uniqueSurfaceID)\r\n\r\n'
    b'{\r\n\r\n'
    b'return m_extent;\r\n\r\n'
    b'}\r\n\r\n'
    b'};\r\n\r\n'
    b'### Loading and saving user geometry',
    b'Here is an example partial implementation of a user geometry client:\r\n\r\n'
    b'```cpp\r\n'
    b'class RectangleClient : public TSLClientUserGeometryEntity\r\n\r\n'
    b'{\r\n\r\n'
    b'private:\r\n\r\n'
    b'TSLEnvelope m_extent;\r\n\r\n'
    b'public:\r\n\r\n'
    b'// Constructor\r\n\r\n'
    b'RectangleClient(TSLTMC left, TSLTMC bottom, TSLTMC right, TSLTMC top)\r\n\r\n'
    b'{\r\n\r\n'
    b'm_extent.corners( left, bottom, right, top ); // bounding box\r\n\r\n'
    b'}\r\n\r\n'
    b'// Destructor\r\n\r\n'
    b'virtual ~RectangleClient()\r\n\r\n'
    b'{\r\n\r\n'
    b'}\r\n\r\n'
    b'// Draw a rectangle using rendering interface\r\n\r\n'
    b'virtual bool draw(int uniqueSurfaceID,\r\n\r\n'
    b'TSLRenderingInterface* renderingInterface,\r\n\r\n'
    b'const TSLEnvelope& extent, TSLRenderLevel renderLevel,\r\n\r\n'
    b'double screenResolution)\r\n\r\n'
    b'{\r\n\r\n'
    b'const int blue = TSLDrawingSurface::getIDOfNearestColour(0,0,255);\r\n\r\n'
    b'// Construct a rectangle\r\n\r\n'
    b'TSLCoord coords[4]; // bottom left, top left, top right, bottom right\r\n\r\n'
    b'coords[0] = m_extent.bottomLeft();\r\n\r\n'
    b'coords[1] = TSLCoord( m_extent.bottomLeft().x(), m_extent.topRight().y() );\r\n\r\n'
    b'coords[2] = m_extent.topRight();\r\n\r\n'
    b'coords[3] = TSLCoord( m_extent.topRight().x(), m_extent.bottomLeft().y() );\r\n\r\n'
    b'// Set up rendering attributes - translucent rectangle\r\n\r\n'
    b'renderingInterface->setupEdgeAttributes( -1, 0, 0.0 );\r\n\r\n'
    b'renderingInterface->setupAreaAttributes( 503, blue );\r\n\r\n'
    b'// Attempt to draw rectangle, return false if fails\r\n\r\n'
    b'return renderingInterface->drawPolygon(coords, _countof(coords));\r\n\r\n'
    b'}\r\n\r\n'
    b'// Save the rectangle\r\n\r\n'
    b'virtual int save(TSLofstream& stream)\r\n\r\n'
    b'{\r\n\r\n'
    b'// Stream out data\r\n\r\n'
    b'...\r\n\r\n'
    b'return RECTANGLE_USER_GEOMETRY_ID; // unique ID of the user geometry type\r\n\r\n'
    b'}\r\n\r\n'
    b'// Return the envelope for this rectangle\r\n\r\n'
    b'virtual TSLEnvelope envelope(int uniqueSurfaceID)\r\n\r\n'
    b'{\r\n\r\n'
    b'return m_extent;\r\n\r\n'
    b'}\r\n\r\n'
    b'};\r\n'
    b'```\r\n\r\n'
    b'### Loading and saving user geometry'
))

# Fix G8: load callback function - & is NOT escaped in TSLifstream/bool
fixes.append(('G8 load callback function',
    b'Here is a skeleton load callback function:\r\n\r\n'
    b'static TSLClientUserGeometryEntity\\* loadUserGeometryCallback(\r\n\r\n'
    b'TSLifstream& stream,\r\n\r\n'
    b'int userGeometryID,\r\n\r\n'
    b'bool& assumeOwnership)\r\n\r\n'
    b'{\r\n\r\n'
    b'// whether returned entities will be freed by MapLink:\r\n\r\n'
    b'assumeOwnership = \\...;\r\n\r\n'
    b'switch (userGeometryID)\r\n\r\n'
    b'{\r\n\r\n'
    b'case RECTANGLE_USER_GEOMETRY_ID:\r\n\r\n'
    b'\\... // stream in client and return it\r\n\r\n'
    b'\\... // etc\r\n\r\n'
    b'default:\r\n\r\n'
    b'return NULL;\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n\r\n'
    b'## Data Layers',
    b'Here is a skeleton load callback function:\r\n\r\n'
    b'```cpp\r\n'
    b'static TSLClientUserGeometryEntity* loadUserGeometryCallback(\r\n\r\n'
    b'TSLifstream& stream,\r\n\r\n'
    b'int userGeometryID,\r\n\r\n'
    b'bool& assumeOwnership)\r\n\r\n'
    b'{\r\n\r\n'
    b'// whether returned entities will be freed by MapLink:\r\n\r\n'
    b'assumeOwnership = ...;\r\n\r\n'
    b'switch (userGeometryID)\r\n\r\n'
    b'{\r\n\r\n'
    b'case RECTANGLE_USER_GEOMETRY_ID:\r\n\r\n'
    b'... // stream in client and return it\r\n\r\n'
    b'... // etc\r\n\r\n'
    b'default:\r\n\r\n'
    b'return NULL;\r\n\r\n'
    b'}\r\n\r\n'
    b'}\r\n'
    b'```\r\n\r\n'
    b'## Data Layers'
))

for name, old, new in fixes:
    found = old in content
    print(f'{name}: found={found}')
    if found:
        content = content.replace(old, new, 1)
    else:
        snippet = old[:80]
        print(f'  snippet: {snippet}')
        snippet_found = snippet in content
        print(f'  snippet found: {snippet_found}')

with open(r'c:\maplink\maplink-docs\pages\developers-guide\geometry-and-overlays.md', 'wb') as f:
    f.write(content)
print('geometry-and-overlays.md written')
